# -*- coding: utf-8 -*-
"""Cropping images in CelebA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hiGIXeip5xaI76lLQR0lQ2P6fuBakz-K
"""

from google.colab import drive
drive.mount('/content/drive')

import os

folder_dir = '../Dataset/trial_test/B2A/modified/original'
img_files = os.listdir(folder_dir)

idx=[]
for i in range(len(img_files)):
    id = img_files[i]
    idx.append(id)
print(idx)

from PIL import Image, ImageDraw
from pathlib import Path
import glob

folder_dir = '../Dataset/trial_test/B2A/modified/original/'

images = Path(folder_dir).glob('*.png')
images = list(images)
count=0
for i in range(len(images)):
  count+=1
  img=Image.open(images[i])
  img.convert('RGB').save(folder_dir + idx[count-1] + '.jpg')

print(idx[0])

from pathlib import Path
import glob
from PIL import Image
folder_dir = '../Dataset/CelebA/img_align_celeba/img_align_celeba/'

images = Path(folder_dir).glob('*.jpg')
images = list(images)
display(Image.open(images[0]))

import numpy as np
from PIL import Image, ImageDraw
from pathlib import Path
import glob
import os

folder_dir = '../Cropped Images/Modified/Class A'
img_files = os.listdir(folder_dir)
idx=[]
for i in range(len(img_files)):
    id = img_files[i]
    idx.append(id)

images = list(Path(folder_dir).glob('*.jpg'))
count=0
for i in range(len(images)):
  count+=1
  img=Image.open(images[i])
  img = img.resize((200,256))
  height,width = img.size
  lum_img = Image.new('L', [height,width] , 0)

  draw = ImageDraw.Draw(lum_img)
  draw.pieslice([(0,0), (height,width)], 0, 360,
              fill = 255, outline = "white")
  img_arr =np.array(img)
  lum_img_arr =np.array(lum_img)
  final_img_arr = np.dstack((img_arr,lum_img_arr))
  crop_img = Image.fromarray(final_img_arr)
  crop_img.convert('RGBA')
  white_crop_img = Image.new("RGBA", crop_img.size, "WHITE")
  white_crop_img.paste(crop_img, mask=crop_img)

  new_path = "../Cropped Images/Modified/Class_A_cropped"
  white_crop_img.convert("RGB").save(new_path + '/' + idx[count-1])